export const defaultKeywords = "GLOD";

export const seo_meta = {
  about: {
    title: "About Us | GLOD",
    description: "",
    language: "Indonesian",
    author: "GLOD",
    image: "",
    twitterCreator: "",
    twitterImage: "",
    ogType: "website",
    ogURL: "",
  },
  catalogue: {
    title: "Catalogue | GLOD",
    description: "",
    language: "Indonesian",
    author: "GLOD",
    image: "",
    twitterCreator: "",
    twitterImage: "",
    ogType: "website",
    ogURL: "",
  },
  detailProduct: {
    title: "Detail Product | GLOD",
    description: "",
    language: "Indonesian",
    author: "GLOD",
    image: "",
    twitterCreator: "",
    twitterImage: "",
    ogType: "website",
    ogURL: "",
  },
  favorite: {
    title: "Favorite | GLOD",
    description: "",
    language: "Indonesian",
    author: "GLOD",
    image: "",
    twitterCreator: "",
    twitterImage: "",
    ogType: "website",
    ogURL: "",
  },
  home: {
    title: "Home | GLOD",
    description: "",
    language: "Indonesian",
    author: "GLOD",
    image: "",
    twitterCreator: "",
    twitterImage: "",
    ogType: "website",
    ogURL: "",
  },
};
